package com.atguigu.mybatisMBG.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.id
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.username
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.password
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.id
     *
     * @return the value of _user.id
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.id
     *
     * @param id the value for _user.id
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.username
     *
     * @return the value of _user.username
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.username
     *
     * @param username the value for _user.username
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.password
     *
     * @return the value of _user.password
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.password
     *
     * @param password the value for _user.password
     *
     * @mbg.generated Sun Nov 14 09:12:18 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    public User() {
    }

    public User(Integer id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }
}